name: Automation

on:
  pull_request:
    branches: [main, development]

jobs:
  build-application:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Check out source code
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # Get app version from package.json
      - name: Set app environment varibale
        run: echo "REACT_APP_VERSION=$(npm pkg get version)" >> $GITHUB_ENV

      # Install dependencies from app
      - name: Intall dependencies
        run: npm i

  test-components:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          npm ci
          npm run build --if-present
          npm test
