name: Automation

on:
  pull_request:
    branches: [main, development]
  repository_dispatch:

jobs:
  test-components:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Check out source code
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # Get app version from package.json
      - name: Set app environment varibale
        run: echo "REACT_APP_VERSION=$(npm pkg get version)" >> $GITHUB_ENV

      # Run tests
      - name: Run tests
        run: |
          npm ci
          npm run build --if-present
          npm test

  deploy-application:
    runs-on: ubuntu-latest
    needs: [test-components]
    if: github.base_ref == 'main'
    steps:
      # Checkout
      - name: Check out source code
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # Get app version from package.json
      - name: Set app environment varibale
        run: echo "REACT_APP_VERSION=$(npm pkg get version)" >> $GITHUB_ENV

      # Install dependencies
      - name: Install dependencies
        run: npm i

      # Build application
      - name: Build application
        run: npm run build

      # Deploy application
      - name: Deploy application
        run: npm run deploy
