name: CI

on:
  pull_request:
    branches: [main, development]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set app environment varibale
        run: echo "REACT_APP_VERSION=$(npm pkg get version)" >> $GITHUB_ENV

      - name: Get env environment variable
        run: echo $REACT_APP_VERSION
