name: Run components tests
run-name: Component tests
on:
  pull_request:
    branches: ["main", "development"]
jobs:
  Install-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - run: npm i
      - run: npm test
